name: Actions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple js Actions
        id: greet
        uses: actions/hello-world-javascript-action
        with:
          who-to-greet: Johny
      - name: Log greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
